### ISSUE TITLE
When running pylint, diff-cover will complain about ignored files

### ISSUE THREAD

**Issue by nedbat** [Bachmann1234/diff_cover#5] opened 2015-03-03 15:59 UTC
When diff-cover runs pylint itself (rather than operating on previously created reports), it runs pylint once per changed file.  One of those files could be an ignored file, because it's matched by the `[MASTER] ignored=` setting in the pylintrc file.  In that case, pylint doesn't ignore the file because the explicit file name on the command line overrides the `ignored` setting in the rc file.

As a result, diff-cover will show pylint errors for ignored files when it runs pylint itself, and won't when it uses pre-created reports.

**Comment by Bachmann1234** [comment] 2015-03-03 17:27
Pylint has been a pain :-P ill look into this when I get a chance.

**Comment by kasium** [comment] 2021-06-15 17:05
@nedbat sorry for the late update :-D

I can't reproduce the issue with pylint 2.8.3. So guess it's not longer relevant

**Comment by Bachmann1234** [comment] 2021-06-15 22:17
Little embarrassing to see my 2015 comment. Closing this for now. Ned knows how to get ahold of me if he needs me.

**Closed by Bachmann1234** 2021-06-15 22:17 UTC
